version: 1.0.{build}

branches:
  only:
  - master

clone_folder: c:\dev\gesture_recognition

environment:
  OPENCV_DIR:   C:/dev/opencv
  access_token:
    secure: YpYf5HPsbcr+3fZmDQZfsTasHYEeWDe5nnGpfq3QNtLLkv11fWOBHhFsJ0ohhZzU
  git_repo: "git@github.com:zeruniverse/Gesture_Recognition.git"
    
install:
  - cinst 7zip.commandline
  - ps:  $dwntool=New-Object System.Net.WebClient
  - ps:  $dwntool.DownloadFile('https://github.com/zeruniverse/Gesture_Recognition/releases/download/V1.0/opencv.zip','c:\dev\opencv.zip')
  - cmd: 7z x c:\dev\opencv.zip -oc:\dev\opencv -y > nul

build:

build_script:
  - xcopy  c:\dev\gesture_recognition c:\dev\bld /s /e /y /i
  - cd c:\dev\bld
  - msbuild /m /p:Configuration=Release /p:Platform="Win32" Gesture_Recognition.sln

on_success:
  - copy /y c:\dev\bld\Release\Gesture_Recognition.exe c:\dev\gesture_recognition\AutoBuild\Gesture_Recognition.exe
  - cd c:\dev\gesture_recognition
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config user.name "AutoBuild"
  - git config user.email "noreply@jeffery.cc"
  - git remote add neworigin "$env:git_repo"
  - git add AutoBuild/Gesture_Recognition.exe
  - git commit -m "Deploy Build $(appveyor_build_version) to GitHub"
  - git push neworigin "master" --quiet > /dev/null 2>&1
  
notifications:
  - provider: Email
    to:
      - zzy8200@gmail.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
