version: 1.0.{build}

branches:
  only:
  - master

clone_folder: c:\dev\gesture_recognition

environment:
  OPENCV_DIR:   C:/dev/opencv

install:
  - cinst 7zip.commandline
  - ps:  $dwntool=New-Object System.Net.WebClient
  - ps:  $dwntool.DownloadFile('https://github.com/zeruniverse/Gesture_Recognition/releases/download/V1.0/opencv.zip','c:\dev\opencv.zip')
  - cmd: 7z x c:\dev\opencv.zip -oc:\dev\opencv -y > nul

build:

build_script:
  - cd c:\dev\gesture_recognition
  - msbuild /m /p:Configuration=Release /p:Platform="Win32" Gesture_Recognition.sln
  
notifications:
  - provider: Email
    to:
      - zzy8200@gmail.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
